# Generated by Django 2.1.3 on 2018-11-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField()),
                ('phone', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
