# Generated by Django 2.1.3 on 2018-11-29 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('responsable', '0002_auto_20181128_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralservice',
            name='planner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
